//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Egress
    {
        public long id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public decimal amount { get; set; }
        public bool erased { get; set; }
        public long doctorId { get; set; }
        public long ingressId { get; set; }
    
        public virtual Doctor Doctor { get; set; }
        public virtual Ingress Ingress { get; set; }
    }
}
