//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Model.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Patient
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Patient()
        {
            this.Ingress = new HashSet<Ingress>();
        }
    
        public long id { get; set; }
        public string idCard { get; set; }
        public string name { get; set; }
        public string lastName { get; set; }
        public string secondSurname { get; set; }
        public string direction { get; set; }
        public string cellPhone { get; set; }
        public string email { get; set; }
        public bool erased { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Ingress> Ingress { get; set; }
    }
}
